os:
    - osx
language: python
env:
    - CC=clang CXX=clang++ LC_ALL="en_US.utf8"
compiler:
    - clang
python:
    - "3.4"
before_install:
install:
    - pip install -r requirements.txt
    - git clone https://github.com/jjangsangy/disqus-python.git disqus
    - pip install -r disqus/requirements.txt
    - python disqus/setup.py install
script:
    - make html
