os:
    - osx
language: python
env:
    - CC=clang
compiler:
    - clang
python:
    - "3.4"
before_install:
install:
    - pip install -r requirements.txt
    - git clone https://github.com/jjangsangy/disqus-python.git disqus
    - cd disqus
    - pip install -r requirements.txt
    - python setup.py install
    - cd ..
script:
    - python plugins/representative_image/test_representative_image.py
    - cd disqus
    - nosetests
    - cd ..
