os:
    - osx
language: python
env:
    - CC=clang CXX=clang++ LC_ALL="en_US.utf8"
compiler:
    - clang
python:
    - "3.4"
before_install:
    - pip install disqus-python
    - git clone https://github.com/getpelican/pelican-plugins.git plugins
install:
    - pip install -r requirements.txt
script:
    - make html
